### PR TITLE
New Feature for reading values between open and close tags.

### PR DESCRIPTION
**Pull request by alirezaarmn**
read values between the open and close tags.

### CODE REVIEW

**Comment by bastibe** [comment]
Thank you for your contribution!

Could you give an example of when this change is useful, and how it would be used?

**Comment by alirezaarmn** [comment]
> Thank you for your contribution!
> 
> Could you give an example of when this change is useful, and how it would be used?

consider the below XML file as an input

[config.txt](https://github.com/bastibe/MatlabXML/files/5786509/config.txt)

let say I want to read the value of 'warmup' tag, So, I need to call 

 `ans.Children(1).Children(1).Children(1).Value`

Also, we can work on a better API for accessing the tag easier by just calling the tag's labels.

**Comment by bastibe** [comment]
This is definitely a missing feature in MatlabXML. 

This PR implements `<warmup>2232</warmup>`. But as far as I can see, it does not implement `<p>mixed <emph>data</emph> and text</p>`. To do this completely, we would need to add text-only child nodes, such that the above example `p` node has three children: one text-node "mixed", then the `emph` node, then another text-node "and text".

Would you like to try to implement that?

**Comment by alirezaarmn** [comment]
sorry for my late response.

> Would you like to try to implement that?

yes, I like to contribute for completing this feature.

> This PR implements <warmup>2232</warmup>. But as far as I can see, it does not implement <p>mixed <emph>data</emph> and text</p>. To do this completely, we would need to add text-only child nodes, such that the above example p node has three children: one text-node "mixed", then the emph node, then another text-node "and text".

 is there any other assumption? Although, I believe using XML like above is not common and standard XML files would not write this way.

**Comment by bastibe** [comment]
I agree that this is not a common use case of XML, but it is very common in other SGML variants, such as HTML. I have seen some XML-based document formats using this feature.

Honestly, I can live with an expressive error message in that case, because I agree that it is not how XML is commonly used.

**Comment by alirezaarmn** [comment]
> I agree that this is not a common use case of XML, but it is very common in other SGML variants, such as HTML. I have seen some XML-based document formats using this feature.
> 
> Honestly, I can live with an expressive error message in that case, because I agree that it is not how XML is commonly used.

So, let me to handle this condition as well, and come back to you with new pull request.

**Pull request closed without merging**
